</section>
</div>
</div>
</main>


<footer class="bg-dark text-light py-3 mt-auto hero-section">
    <div class="container">
        <div class="row mt-3 md-4 d-flex justify-content-between">
            <div class="col-md-4">
                <h5>
                    <a href="index.php" class="text-decoration-none footer-brand">
                        <strong>🎓 BCS</strong> Placements
                    </a>
                </h5>
                <p class="text-white"><i>Connecting students with placement opportunities.</i></p>
            </div>

            <div class="col-md-3">
                <h6>Quick Links</h6>
                <ul class="list-unstyled footer-links">
                    <li><a href="index.php" class="text-decoration-none text-muted">Home</a></li>
                    <li><a href="login.php" class="text-decoration-none text-muted">Login/Register</a></li>
                    <li><a href="placements.php" class="text-decoration-none text-muted">Browse Placements</a></li>
                    <li><a href="index.php#why-placements" class="text-decoration-none text-muted">Why Placements?</a></li>
                    <li><a href="faqs.php" class="text-decoration-none text-muted">FAQs</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h6>Resources</h6>
                <ul class="list-unstyled footer-links">
                    <li><a href="http://www.bcs.org/category/18153" class="text-decoration-none text-muted" target="_blank">BCS Manchester</a></li>
                    <li><a href="https://www.sfia-online.org/en" class="text-decoration-none text-muted" target="_blank">SFIA Framework</a></li>
                    <li><a href="https://greatermanchester-ca.gov.uk/what-we-do/digital/" class="text-decoration-none text-muted" target="_blank">GMCA Digital City Region</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <h6>Company</h6>
                <ul class="list-unstyled footer-links">
                    <li><a href="about.php" class="text-decoration-none text-muted">About Us</a></li>
                    <li><a href="contact.php" class="text-decoration-none text-muted">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <hr class="my-3">
        <div class="container text-center">
            <span class="text-white">Copyright © 2025 BCS Placements. All Rights Reserved.</span>
        </div>
    </div>
</footer>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>